import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import axios from "axios";
import Image from "next/image";
import useSWR from "swr";
import styles from "../styles/Home.module.scss";

const fetcher = (url: string) => fetch(url).then((res) => res.json());

const Home: NextPage<{ pocketmon: PocketmonAPI }> = ({ pocketmon }) => {
  return (
    <>
      <Head>
        <title>Pocketmon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className={styles.title}>pocketmon list~~</p>
      <div className={styles.container}>
        {pocketmon.results.map((info) => (
          <div key={info.name} className={styles.item}>
            <Link href={`/${info.name}`}>{info.name}</Link>
          </div>
        ))}
      </div>
    </>
  );
};

Home.getInitialProps = async (ctx) => {
  const response = await axios.get<PocketmonAPI>(
    "https://pokeapi.co/api/v2/pokemon?limit=20"
  );

  return { pocketmon: response.data };
};
export default Home;
