import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import useSWR from "swr";
import styles from "../styles/Home.module.css";

const fetcher = (url: string) => fetch(url).then((res) => res.json());

const Home: NextPage = () => {
  const { data, error } = useSWR("/api/list", fetcher);
  console.log(data.results);
  return (
    <div className={styles.container}>
      <Head>
        <title>Pocketmon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

Home.getInitialProps = (ctx) => {
  if (ctx.req && ctx.res) {
  }
  return {};
};
export default Home;
